[package]
name = "raskrasser"
version = "0.1.0"
authors = ["Roman Chumak <p4@phygitalism.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
obj = "0.10.1"
bvh = "0.3.2"
camera_ss = "0.1.1"
nalgebra = "0.18"
